# Cloudflare Pages configuration for bt-studio
name = "bt-studio"
compatibility_date = "2024-01-01"

[env.production]
name = "bt-studio"

[env.preview]
name = "bt-studio-preview"

# Build configuration
[build]
command = "pnpm build:bt-studio"
cwd = "../.."
publish = "apps/bt-studio/dist"

# Environment variables (set these in Cloudflare dashboard)
[vars]
NODE_ENV = "production"
VITE_APP_NAME = "BT Studio"
VITE_APP_VERSION = "1.0.0"

# Headers for SPA routing
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# SPA fallback for client-side routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
